### ISSUE TITLE
Rename this repo to `.github`

### ISSUE THREAD

**Issue by mkungla** [solidity-docs/.github#9]
I suggest renaming this repo to Github's special repo `.github` then README.md file would appear in orgs main page and you can keep [docs](https://github.com/solidity-docs) community files in single repo. 

This Github feature allows you to have central place for files e.g  Contributing Guidelines, LICENSE, issue templates etc. for all translation org repos. 

I have good example of use case in github org which I also provided as example for #8 proposal.

- e.g. org [.gihub](https://github.com/howijd/.github) repo
- in this repo there is `profile/README.md` which appears then as https://github.com/howijd org page
- you can learn more about `.github` special repository here https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile

**Comment by franzihei** [comment]
I didn't even know of this option, sounds really cool! I'll explore this option soon.

**Comment by cameel** [comment]
We talked about this today. We'll go with this change but there's a risk that renaming the repo now might throw off the gitcoin bot (it's tracking #8) so I think it's better to do this only after we have that issue closed.

**Comment by cameel** [comment]
Repo renamed. README moved in #36.
